name: Build APK
on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Обновлено до v4
    
    - name: Setup Python
      uses: actions/setup-python@v4  # Обновлено до v4
      with:
        python-version: "3.11"  # Используем актуальную версию Python
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        pip install buildozer
    
    - name: Build APK
      run: |
        buildozer init
        echo -e "\n[app]\nrequirements = python3, pygame, kivy" >> buildozer.spec
        buildozer -v android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4  # Обновлено до v4
      with:
        name: naturalomer
        path: bin/*.apk
