name: Build APK
on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"  # Меняем на проверенную версию

    - name: Install dependencies
      run: |
        sudo apt-get update
        # Добавляем системные зависимости
        sudo apt-get install -y \
            openjdk-17-jdk \
            zlib1g-dev \
            build-essential \
            libssl-dev \
            python3-venv
        # Устанавливаем Python-пакеты
        pip install --upgrade pip wheel setuptools
        pip install cython==0.29.36  # Явно указываем версию
        pip install buildozer

    - name: Configure and build
      run: |
        buildozer init
        # Правим spec-файл
        sed -i "s/^requirements = .*/requirements = python3, sdl2, pygame, kivy/" buildozer.spec
        sed -i "s/^android.ndk = .*/android.ndk = 25b/" buildozer.spec
        sed -i "s/^android.sdk = .*/android.sdk = 26.1.1/" buildozer.spec
        
        # Собираем APK
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: naturalomer
        path: bin/*.apk
